#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xBBC17EBB1396F2F7 (stuart@debian.org)
#
Name     : pypi-python_debian
Version  : 0.1.43
Release  : 4
URL      : https://files.pythonhosted.org/packages/0c/c1/97829fac1e9889dd0ea0d7c018bbe3901753499a1eaafa7747f718257ef2/python-debian-0.1.43.tar.gz
Source0  : https://files.pythonhosted.org/packages/0c/c1/97829fac1e9889dd0ea0d7c018bbe3901753499a1eaafa7747f718257ef2/python-debian-0.1.43.tar.gz
Source1  : https://files.pythonhosted.org/packages/0c/c1/97829fac1e9889dd0ea0d7c018bbe3901753499a1eaafa7747f718257ef2/python-debian-0.1.43.tar.gz.asc
Summary  : Debian package related modules
Group    : Development/Tools
License  : GPL-2.0+
Requires: pypi-python_debian-python = %{version}-%{release}
Requires: pypi-python_debian-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(chardet)

%description
The `debian` Python modules work with Debian-related data formats,
providing a means to read data from files involved in Debian packaging,
and the distribution of Debian packages. The ability to create or edit
the files is also available for some formats.

%package python
Summary: python components for the pypi-python_debian package.
Group: Default
Requires: pypi-python_debian-python3 = %{version}-%{release}

%description python
python components for the pypi-python_debian package.


%package python3
Summary: python3 components for the pypi-python_debian package.
Group: Default
Requires: python3-core
Provides: pypi(python_debian)
Requires: pypi(chardet)

%description python3
python3 components for the pypi-python_debian package.


%prep
%setup -q -n python-debian-0.1.43
cd %{_builddir}/python-debian-0.1.43

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1648618510
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
